language: generic
services:
- docker
script:
- docker build --no-cache --pull -t quay.io/wisvch/mand:$TRAVIS_BUILD_NUMBER .
after_success:
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then
    docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io;
    docker push quay.io/wisvch/mand:$TRAVIS_BUILD_NUMBER;
  fi
notifications:
  email: false
